version: 0.2

phases:
  pre_build:
    commands:
      # Install dependencies for server-side code
      - npm install
      # Install dependencies for client-side code
      - npm run client-install
  build:
    commands:
      # Build client-side code
      - cd client && npm run build
    
  cache:
    paths:
      - 'node_modules/**/*' # Cache `node_modules` for faster `yarn` or `npm i`
      - '.next/cache/**/*' # Cache Next.js for faster application rebuilds

artifacts:
  files:
    - '**/*'
  discard-paths: no  
  base-directory: ./
  