version: 0.2

phases:
  pre_build:
    commands:
      # Install dependencies for server-side code
      - npm install
      # Install dependencies for client-side code
      - npm run client-install
  build:
    commands:
      # Build client-side code
      - cd client && npm run build

  post_build:
    commands:
      - cd ../ && npm run start
    
artifacts:
  files:
    - '**/*'
  discard-paths: no  
  base-directory: ./
  